#--------------------------------------------------------------------------------------------------
# See 'Readme.md' for information
#--------------------------------------------------------------------------------------------------

before_script:
  - git config --global http.proxy "${HTTP_PROXY}"
  - git config --global https.proxy "${HTTPS_PROXY}"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
  - export http_proxy="${HTTP_PROXY}"
  - export https_proxy="${HTTPS_PROXY}"
  - export no_proxy="${NO_PROXY}"
  - export GITTAG=`git describe --tags --abbrev=0 2> /dev/null`
  - git config --list
  - env

stages:
  - build
  - test

build:gta:
  stage: build
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - make all
  artifacts:
    paths:
      - "out/trustagent-*.bin"
      - "out/tagent"
    expire_in: 1 week

test:
  stage: test
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - make unit_test
  artifacts:
    paths:
      - "out/cover.html"      
