#--------------------------------------------------------------------------------------------------
# See 'Readme.md' for information
#--------------------------------------------------------------------------------------------------

before_script:
  - git config --global http.proxy http://proxy-us.intel.com:911
  - git config --global https.proxy http://proxy-us.intel.com:911
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devtools.intel.com".insteadOf "https://gitlab.devtools.intel.com"
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:911
  - export no_proxy=127.0.0.1,localhost,gitlab.devtools.intel.com
  - cd $CI_PROJECT_DIR

stages:
  - build
  - test


build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - make installer
  artifacts:
    paths:
      - "out/trustagent-*.bin"
      - "out/tagent"
    expire_in: 1 week

test:
  stage: test
#  image: gta-devel
  tags:
    - gta-test
#  dependencies:
#    - build:gta
  script:
    - go test ./... -tags=integration -coverpkg=./... -coverprofile cover.out
    - go tool cover -func cover.out
    - go tool cover -html=cover.out -o cover.html
  artifacts:
    paths:
      - "cover.html"